#!/bin/bash
# Persist the CIFS mount of the Pi's recordings share across Unraid reboots.
#
# Unraid's rootfs lives in RAM and is rebuilt every boot, so a mount made by
# hand disappears. /boot/config/go survives on the flash drive and runs at boot.
#
# Run as root, once:
#     PI_HOST=10.0.0.5 bash install-mount.sh
#
# Idempotent — running it again refreshes the helper and leaves credentials be.

set -euo pipefail

# The Pi's address is NOT hardcoded: this file is committed, and the address is
# infrastructure detail. It is baked into the generated helper on the flash
# drive instead.
PI_HOST="${PI_HOST:-}"
if [[ -z "${PI_HOST}" ]]; then
    read -rp "Pi hostname or IP (e.g. 10.0.0.5 or your-pi.local): " PI_HOST
fi
[[ -n "${PI_HOST}" ]] || { echo "PI_HOST is required" >&2; exit 1; }

SHARE="//${PI_HOST}/recordings"
MOUNTPOINT="/mnt/remotes/muse_recordings"
CRED="/boot/config/muse-recordings.cred"
HELPER="/boot/config/mount-muse-recordings.sh"
GO="/boot/config/go"

echo "==> credentials (${CRED}, root-only)"
if [[ -f "${CRED}" ]]; then
    echo "    already exists, leaving it alone"
else
    read -rp "SMB username for ${SHARE}: " SMB_USER
    read -rsp "SMB password: " SMB_PASS; echo
    printf 'username=%s\npassword=%s\n' "${SMB_USER}" "${SMB_PASS}" > "${CRED}"
    chmod 600 "${CRED}"
fi

echo "==> writing ${HELPER}"
# Unquoted heredoc so PI_HOST/paths are baked in; the helper takes no input.
cat > "${HELPER}" <<HELPER_EOF
#!/bin/bash
# Generated by install-mount.sh — do not edit by hand; re-run the installer.
#
# Mounts the Muse recordings share once the array is up. Backgrounded from
# /boot/config/go, because at boot /mnt/user may not exist yet.

SHARE="${SHARE}"
MOUNTPOINT="${MOUNTPOINT}"
CRED="${CRED}"

for _ in \$(seq 1 60); do
    [[ -d /mnt/user ]] && break
    sleep 5
done

mkdir -p "\${MOUNTPOINT}" /mnt/user/data/eeg/output

# The container binds /mnt/remotes with rslave propagation so a mount landing
# after the container starts (the normal case at boot) becomes visible inside
# it. That needs the host side shared, and propagation flags do not survive a
# reboot — so set it every time, before mounting.
mount --make-rshared /mnt/remotes 2>/dev/null || true

mountpoint -q "\${MOUNTPOINT}" && exit 0

# Retry rather than giving up after one attempt. At boot the Pi may still be
# starting (so the share is not yet served), and if the address is an mDNS name
# then avahi may not have come up here either. A single failed attempt plus
# 'nofail' would leave an empty directory and no error — the exact silent
# failure this project keeps producing.
#
# vers=3.1.1: forcing 3.0 makes the share enumerate EMPTY against modern Samba
#             (files readable by name, but ls returns nothing).
# cache=none,actimeo=0: the default cache serves stale content, which has
#             silently truncated a recording mid-analysis.
for attempt in \$(seq 1 30); do
    if mount -t cifs "\${SHARE}" "\${MOUNTPOINT}" \\
        -o "credentials=\${CRED},ro,vers=3.1.1,cache=none,actimeo=0,uid=99,gid=100,iocharset=utf8,nofail"
    then
        logger -t muse "mounted \${SHARE} on attempt \${attempt}"
        exit 0
    fi
    logger -t muse "mount attempt \${attempt}/30 for \${SHARE} failed; retrying in 20s"
    sleep 20
done
logger -t muse "GAVE UP mounting \${SHARE} after 30 attempts (10 minutes)"
exit 1
HELPER_EOF

# /boot is vfat with fmask=0177 — the execute bit can never be set there, so the
# helper must always be invoked through bash, never executed directly.
chmod +x "${HELPER}" 2>/dev/null || true

echo "==> wiring into ${GO}"
if grep -q "mount-muse-recordings" "${GO}"; then
    echo "    already referenced, nothing to do"
else
    cp "${GO}" "${GO}.bak-muse-$(date +%Y%m%d%H%M%S)"
    cat >> "${GO}" <<'GO_EOF'

# Mount the Muse recordings share from the Pi (backgrounded; waits for array).
# Invoked via bash: /boot is vfat and cannot carry an execute bit.
bash /boot/config/mount-muse-recordings.sh &
GO_EOF
    echo "    appended (previous version backed up alongside)"
fi

echo "==> mounting now"
bash "${HELPER}"
if mountpoint -q "${MOUNTPOINT}"; then
    echo "OK: ${MOUNTPOINT} is mounted"
    ls -la "${MOUNTPOINT}" | tail -3
else
    echo "WARNING: mount did not succeed — check: logger output, dmesg," >&2
    echo "         that ${PI_HOST} is reachable, and the credentials." >&2
    exit 1
fi
